package edu.sjsu.cmpe272.issuesgateway;

/*
 * Author: Sai Vineetha Tirumalla
 * Contribution: Spring Boot application entry point (generated by Spring Initializr)
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class IssuesGatewayApplication {

	public static void main(String[] args) {
		SpringApplication.run(IssuesGatewayApplication.class, args);
	}

}
